export enum ACTIONS {
    SET_IS_OPEN_HEADER = "SET_IS_OPEN_HEADER",
    SET_EMAIL = "SET_EMAIL",
    SET_USER_NAME = "SET_USER_NAME",
    SET_PASSWORD = "SET_PASSWORD",
    SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD",
    SET_EMAIL_LOGIN = "SET_EMAIL_LOGIN",
    SET_PASSWORD_LOGIN = "SET_PASSWORD_LOGIN",
    SET_EMAIL_RESET_PASSWORD = "SET_EMAIL_RESET_PASSWORD",
    SET_NEW_PASSWORD = "SET_NEW_PASSWORD",
    SET_NEW_PASSWORD_CONFIRM = "SET_NEW_PASSWORD_CONFIRM",

    SEND_LOGIN_DATA_ACTION = "SEND_LOGIN_DATA_ACTION",
    SEND_LOGIN_DATA_ERROR_ACTION = "SEND_LOGIN_DATA_ERROR_ACTION",
    SEND_LOGIN_DATA_SUCCESS_ACTION = "SEND_LOGIN_DATA_SUCCESS_ACTION",

    SEND_REGISTRATION_DATA_ACTION = "SEND_REGISTRATION_DATA_ACTION",
    SEND_REGISTRATION_DATA_ERROR_ACTION = "SEND_REGISTRATION_DATA_ERROR_ACTION",
    SEND_REGISTRATION_DATA_SUCCESS_ACTION = "SEND_REGISTRATION_DATA_SUCCESS_ACTION",

    SEND_REGISTRATION_CONFIRMATION = "SEND_REGISTRATION_CONFIRMATION",

    SET_POSTS_ACTION = "SET_POSTS_ACTION",
    SET_MY_POSTS_ACTION = "SET_MY_POSTS_ACTION",
    GET_POSTS_ACTION = "GET_POSTS_ACTION",
    GET_MY_POSTS_ACTION = " GET_MY_POSTS_ACTION",

    SET_PROFILE = "SET_PROFILE",

    GET_SELECTED_POST_ACTION = "GET_SELECTED_POST_ACTION",
    SET_SELECTED_POST_ACTION = "SET_SELECTED_POST_ACTION",

    SET_MY_POST_ERROR_ACTION = "SET_MY_POST_ERROR_ACTION",

    SEND_POST_ACTION = "SEND_POST_ACTION"
}